{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "No of Patient with Arrhythmia",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(dxname) FROM ecg WHERE dxname <> 'NOF' LIMIT 46000 "
    }
   ]
  },
  {
   "title": "No of Patient without Arrhythmia",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(dxname) FROM ecg WHERE dxname = 'NOF' LIMIT 46000 "
    }
   ]
  },
  {
   "title": "Top 5 Arrhythmia Diseases among Patients",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(dxname), dxname FROM ecg WHERE dxname <> 'NOF' GROUP BY dxname ORDER BY COUNT(dxname) DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Distribution of Gender with Arrhythmias",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT gender, COUNT(gender) FROM ecg WHERE dxname <> 'NOF' GROUP BY gender LIMIT 4600 "
    }
   ]
  },
  {
   "title": "Top 5 Arrhythmia Diseases among Female",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(dxname), dxname FROM ecg WHERE (dxname <> 'NOF' AND gender = 'Female') GROUP BY dxname ORDER BY COUNT(dxname) DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Top 5 Arrhythmia Diseases among Male",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(dxname), dxname FROM ecg WHERE (dxname <> 'NOF' AND gender = 'Male') GROUP BY dxname ORDER BY COUNT(dxname) DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Top 5 Arrhythmia Diseases in Age Group 0-40",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(dxname), dxname FROM ecg WHERE (dxname <> 'NOF' AND age > 0 AND age <= 40) GROUP BY dxname ORDER BY COUNT(dxname) DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Top 5 Arrhythmia Diseases in Age Group 40-90",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(dxname), dxname FROM ecg WHERE (dxname <> 'NOF' AND age > 40 AND age <= 90) GROUP BY dxname ORDER BY COUNT(dxname) DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Distribution of Age with Arrhythmias",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT age, COUNT(age) FROM ecg WHERE (dxname <> 'NOF' AND age <> 0) GROUP BY age LIMIT 4600 "
    }
   ]
  },
  {
   "title": "Distribution of Heart Rate(hr) with Arrhythmias",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT hr, COUNT(hr) FROM ecg WHERE dxname <> 'NOF' GROUP BY hr LIMIT 4600 "
    }
   ]
  },
  {
   "title": "Age Heart Rate Scatter Plot",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT age, hr FROM ecg LIMIT 50 "
    }
   ]
  }
 ]
}